server.port=8081
spring.thymeleaf.cache=false

# MySQL properties
# db.driver=com.mysql.cj.jdbc.Driver
# db.url=jdbc:mysql://localhost:3306/spring_hiber_crud?allowPublicKeyRetrieval=true&verifyServerCertificate=false&useSSL=false&requireSSL=false&useLegacyDatetimeCode=false&amp&serverTimezone=UTC
# db.username=root
# db.password=admin

# Hibernate properties
hibernate.show_sql=true
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/spring_hiber_crud?allowPublicKeyRetrieval=true&verifyServerCertificate=false&useSSL=false&requireSSL=false&useLegacyDatetimeCode=false&amp&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=admin
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# devtools
spring.webresources.cache.cachecontrol.max-age=0

spring.devtools.restart.enabled=true
# spring.devtools.livereload.enabled=true
spring.devtools.restart.poll-interval=1000
spring.devtools.restart.quiet-period=400


# ?????????? ???? ???????? - ??? ????????? ????????? ?????? HTML ??? ???????????? ?????????? (??? ????? ???? ????????)
spring.thymeleaf.prefix=file:src/main/resources/templates/

# DevTools ?????????

